version: "3.3"
services:
  pethernet:
    image: yadsendewlung/sixtyfiver-pethernet:latest
    ports:
      - "5000:${PETHERNET_PORT}"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SERVER_PORT=${PETHERNET_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
      - PETHERNET_CONTRACT_ADDRESS=${PETHERNET_CONTRACT_ADDRESS}
      - MINISTRY_OF_HEALTH_ADDRESS=${MINISTRY_OF_HEALTH_ADDRESS}
    volumes:
      - public:/tmp/public

  sixtyfiver-gateway:
    image: yadsendewlung/sixtyfiver-gateway:latest
    ports:
      - "8080:${SIXTYFIVER_PORT}"
    environment:
      - SIXTYFIVER_PORT=${SIXTYFIVER_PORT}
      - NGINX_PORT=${NGINX_PORT}
      - PETHERNET_HOST=${PETHERNET_HOST}
      - PETHERNET_PORT=${PETHERNET_PORT}
    volumes:
      - public:/tmp/public
volumes:
  public:
  data:
